buildscript {
    repositories {
        mavenCentral()
        gradlePluginPortal()
    }
    dependencies {
        // Shadow plugin phiên bản 2.0.4 tương thích tốt với Gradle 4.9
        classpath 'com.github.jengelman.gradle.plugins:shadow:2.0.4'
    }
}

apply plugin: 'java'
apply plugin: 'application'
apply plugin: 'com.github.johnrengelman.shadow'

group = 'gadgetinspector'
version = '1.0-SNAPSHOT'

sourceCompatibility = 1.8
targetCompatibility = 1.8

mainClassName = 'gadgetinspector.GadgetInspector'

repositories {
    mavenCentral()
}

tasks.withType(JavaCompile) {
    options.encoding = "UTF-8"
}

sourceSets {
    main {
        resources {
            srcDirs = ["src/main/java/gadgetinspector/resultOutput/resources"]
        }
    }
}

dependencies {
    compile "org.ow2.asm:asm:9.6"
    compile "org.ow2.asm:asm-commons:9.6"
    
    compile "com.google.guava:guava:28.2-jre"
    compile 'org.slf4j:slf4j-api:1.7.25'
    compile 'org.slf4j:slf4j-log4j12:1.7.25'


    if (project.hasProperty("inspectGroup")) {
        compile "${project.inspectGroup}:${project.inspectName}:${project.inspectVersion}"
    }
}


shadowJar {
    baseName = 'gadget-inspector'
    classifier = 'all'
}


if (project.hasProperty("inspectConfig")) {
    task runInspect(type: JavaExec) {
        classpath = sourceSets.main.runtimeClasspath
        main = "gadgetinspector.GadgetInspector"
        args = ["--config", project.inspectConfig]
    }
}